const SCHEMA_VERSION = "1.0.0";

function createEmptyProfile(profileId, now = new Date().toISOString()) {
  return {
    meta: {
      schema_version: SCHEMA_VERSION,
      profile_id: profileId,
      created_at: now,
      updated_at: now,
      total_sessions: 0,
      total_questions_answered: 0,
      completeness_score: 0,
      completeness_by_area: {
        identity: 0,
        interests_and_preferences: 0,
        behavioral_patterns: 0,
        social_dynamics: 0,
        professional: 0,
        personality: 0,
        emotional_profile: 0,
        values_and_beliefs: 0,
        cognitive_patterns: 0,
        motivations_and_drives: 0,
        self_concept: 0,
        life_narrative: 0,
        synthesis: 0,
      },
      confidence_scores: {},
      confidence_by_block: {
        identity: 0,
        interests_and_preferences: 0,
        behavioral_patterns: 0,
        social_dynamics: 0,
        professional: 0,
        personality: 0,
        emotional_profile: 0,
        values_and_beliefs: 0,
        cognitive_patterns: 0,
        motivations_and_drives: 0,
        self_concept: 0,
        life_narrative: 0,
        synthesis: 0,
      },
      data_lineage: {},
      consent: {
        accepted: false,
        accepted_at: "",
        version: "",
        source: "",
      },
      safety: {
        crisis_events_count: 0,
        last_crisis_at: "",
      },
      phases_completed: [],
      deepening_sessions: 0,
      last_phase: "phase_01",
      language: "pt-BR",
    },
    identity: {
      full_name: "",
      preferred_name: "",
      age: null,
      date_of_birth: "",
      gender: "",
      pronouns: "",
      nationality: "",
      ethnicity_cultural_background: "",
      location: {
        current_city: "",
        current_country: "",
        born_in: "",
        places_lived: [],
      },
      languages: [],
      family: {
        marital_status: "",
        partner_description: "",
        children: [],
        siblings: [],
        relationship_with_parents: "",
        family_dynamics_summary: "",
        family_role: "",
      },
      physical_self: {
        self_description: "",
        relationship_with_body: "",
        health_conditions_relevant: [],
      },
    },
    interests_and_preferences: {
      hobbies: [],
      passions: [],
      topics_of_fascination: [],
      media: {
        books: { genres: [], favorites: [], reading_frequency: "" },
        movies_series: { genres: [], favorites: [], frequency: "" },
        music: { genres: [], artists: [], role_of_music: "" },
        podcasts: { topics: [], favorites: [] },
        games: { types: [], favorites: [] },
        social_media: { platforms: [], usage_pattern: "", content_consumed: "" },
      },
      food: {
        preferences: [],
        restrictions: [],
        relationship_with_food: "",
        cooking_interest: "",
      },
      travel: {
        style: "",
        favorite_destinations: [],
        dream_destinations: [],
        frequency: "",
        motivation: "",
      },
      aesthetics: {
        style_preference: "",
        color_preferences: [],
        environment_preferences: "",
        beauty_standards: "",
      },
      technology: {
        relationship: "",
        adoption_speed: "",
        preferences: [],
        concerns: [],
      },
    },
    behavioral_patterns: {
      daily_routine: {
        morning: "",
        afternoon: "",
        evening: "",
        night: "",
        consistency_level: "",
      },
      habits: {
        positive: [],
        negative: [],
        trying_to_build: [],
        trying_to_break: [],
      },
    },
    social_dynamics: {
      social_energy: {
        introversion_extraversion_spectrum: null,
        social_battery_capacity: "",
        recharge_method: "",
        ideal_social_frequency: "",
      },
      communication_style: {
        primary_style: "",
        assertiveness_level: null,
        directness: null,
        formality_preference: "",
        humor_style: "",
        listening_quality: null,
        storytelling_tendency: null,
        verbal_vs_written_preference: "",
      },
      conflict_style: {
        primary: "",
        avoidance_tendency: null,
        anger_expression: "",
        forgiveness_pattern: "",
        grudge_holding: null,
      },
      leadership_style: {
        natural_tendency: "",
        preferred_role_in_groups: "",
        authority_relationship: "",
      },
      trust_patterns: {
        trust_speed: "",
        trust_criteria: [],
        betrayal_recovery: "",
        vulnerability_comfort: null,
      },
      relationship_patterns: {
        friendship_style: "",
        romantic_style: "",
        professional_relationships: "",
        family_relationships: "",
        attachment_in_practice: "",
      },
      social_perception: {
        how_they_think_others_see_them: "",
        how_they_want_to_be_seen: "",
        social_masks_used: [],
        authenticity_level: null,
      },
      boundaries: {
        setting_ability: null,
        respecting_others: null,
        common_boundary_issues: [],
      },
      influence_susceptibility: {
        peer_pressure: null,
        authority_influence: null,
        social_media_influence: null,
        independent_thinking: null,
      },
    },
    professional: {
      current_role: "",
      career_history: [],
      industry: "",
      expertise_areas: [],
      skills: {
        technical: [],
        soft: [],
        unique_combinations: [],
      },
      work_style: {
        preferred_environment: "",
        autonomy_need: null,
        structure_need: null,
        collaboration_preference: "",
        deadline_behavior: "",
        perfectionism_level: null,
        work_life_balance_priority: null,
      },
      professional_identity: {
        what_defines_them_professionally: "",
        dream_role: "",
        professional_values: [],
        deal_breakers: [],
      },
      ambitions: {
        short_term: [],
        long_term: [],
        ultimate_professional_goal: "",
      },
      professional_strengths: [],
      professional_weaknesses: [],
      relationship_with_money: {
        mindset: "",
        spending_pattern: "",
        saving_pattern: "",
        financial_goals: "",
        money_anxiety_level: null,
      },
      career_satisfaction_level: null,
      motivation_summary: "",
    },
    personality: {
      big_five: {
        openness: {
          score: null,
          level: "",
          facets: {
            imagination: null,
            artistic_interest: null,
            emotionality: null,
            adventurousness: null,
            intellect: null,
            liberalism: null,
          },
          evidence: [],
        },
        conscientiousness: {
          score: null,
          level: "",
          facets: {
            self_efficacy: null,
            orderliness: null,
            dutifulness: null,
            achievement_striving: null,
            self_discipline: null,
            cautiousness: null,
          },
          evidence: [],
        },
        extraversion: {
          score: null,
          level: "",
          facets: {
            friendliness: null,
            gregariousness: null,
            assertiveness: null,
            activity_level: null,
            excitement_seeking: null,
            cheerfulness: null,
          },
          evidence: [],
        },
        agreeableness: {
          score: null,
          level: "",
          facets: {
            trust: null,
            morality: null,
            altruism: null,
            cooperation: null,
            modesty: null,
            sympathy: null,
          },
          evidence: [],
        },
        neuroticism: {
          score: null,
          level: "",
          facets: {
            anxiety: null,
            anger: null,
            depression: null,
            self_consciousness: null,
            immoderation: null,
            vulnerability: null,
          },
          evidence: [],
        },
      },
      mbti_approximation: {
        type: "",
        dominant_function: "",
        auxiliary_function: "",
        confidence: null,
        evidence: [],
      },
      enneagram_approximation: {
        core_type: null,
        wing: null,
        tritype: "",
        instinctual_variant: "",
        evidence: [],
      },
      temperament: {
        primary: "",
        secondary: "",
        description: "",
      },
      cognitive_style: {
        analytical_vs_intuitive: null,
        detail_vs_big_picture: null,
        sequential_vs_random: null,
        verbal_vs_visual: null,
        convergent_vs_divergent: null,
      },
      summary: "",
    },
    emotional_profile: {
      emotional_baseline: {
        default_mood: "",
        emotional_range: "",
        emotional_intensity: "",
        emotional_stability: "",
      },
      emotional_intelligence: {
        self_awareness: null,
        self_regulation: null,
        motivation: null,
        empathy: null,
        social_skills: null,
        overall_eq: null,
      },
      attachment_style: {
        primary: "",
        secondary: "",
        in_romantic_relationships: "",
        in_friendships: "",
        with_authority: "",
        evidence: [],
      },
      emotional_triggers: [],
      coping_mechanisms: {
        healthy: [],
        unhealthy: [],
        primary_defense_mechanisms: [],
        under_stress: "",
        under_grief: "",
        under_conflict: "",
        under_pressure: "",
      },
      emotional_needs: [],
      emotional_expression_style: "",
    },
    values_and_beliefs: {
      core_values: [],
      hierarchy_of_values: [],
      worldview: {
        summary: "",
        optimist_vs_pessimist: null,
        idealist_vs_realist: null,
        individualist_vs_collectivist: null,
      },
      moral_foundations: {
        care_harm: null,
        fairness_cheating: null,
        loyalty_betrayal: null,
        authority_subversion: null,
        sanctity_degradation: null,
        liberty_oppression: null,
      },
      ethical_framework: "",
      political_orientation: {
        economic: "",
        social: "",
        summary: "",
      },
      spiritual_religious: {
        beliefs: "",
        practices: "",
        importance: null,
      },
      philosophical_stances: [],
      non_negotiables: [],
      things_tolerated_but_disliked: [],
    },
    cognitive_patterns: {
      decision_making: {
        style: "",
        speed: "",
        factors_prioritized: [],
        analysis_paralysis_prone: null,
        gut_vs_data: null,
        regret_pattern: "",
      },
      problem_solving: {
        approach: "",
        creativity_level: null,
        persistence_level: null,
        asks_for_help_when: "",
        preferred_tools: [],
      },
      learning: {
        style: "",
        speed: "",
        preferred_formats: [],
        retention_strengths: "",
        motivation_to_learn: "",
      },
      cognitive_biases_prone: [],
      attention_patterns: {
        focus_duration: "",
        multitasking_ability: "",
        distraction_triggers: [],
        flow_state_triggers: [],
      },
      memory_patterns: {
        strongest_memory_type: "",
        nostalgic_tendency: null,
        forgets_easily: [],
      },
      thinking_patterns: {
        inner_monologue: "",
        rumination_tendency: null,
        catastrophizing_tendency: null,
        black_white_thinking: null,
        overthinking_tendency: null,
      },
      creativity: {
        level: null,
        expression_channels: [],
        creative_process: "",
      },
      risk_tolerance: {
        financial: null,
        physical: null,
        social: null,
        professional: null,
        emotional: null,
      },
    },
    motivations_and_drives: {
      core_motivations: [],
      intrinsic_motivators: [],
      extrinsic_motivators: [],
      what_gets_them_out_of_bed: "",
      what_keeps_them_up_at_night: "",
      deepest_fears: [],
      deepest_desires: [],
      life_goals: {
        achieved: [],
        in_progress: [],
        future: [],
        abandoned: [],
      },
      purpose_sense: {
        has_clear_purpose: null,
        purpose_statement: "",
        meaning_sources: [],
      },
      self_actualization: {
        current_level: "",
        barriers: [],
        growth_areas: [],
      },
    },
    self_concept: {
      self_image: "",
      self_esteem_level: null,
      self_compassion_level: null,
      ideal_self: "",
      gap_real_vs_ideal: "",
      identity_anchors: [],
      insecurities: [],
      confidence_areas: [],
      inner_critic: {
        intensity: null,
        common_messages: [],
        origin: "",
      },
      self_awareness_level: null,
      personal_growth_orientation: null,
      relationship_with_past_self: "",
      relationship_with_future_self: "",
    },
    life_narrative: {
      life_chapters: [],
      turning_points: [],
      formative_experiences: [],
      traumas_acknowledged: [],
      proudest_moments: [],
      deepest_regrets: [],
      unresolved_issues: [],
      life_philosophy_statement: "",
      personal_mantras: [],
      legacy_desire: "",
    },
    synthesis: {
      core_essence_paragraph: "",
      in_three_words: [],
      unique_combination: "",
      primary_archetypes: [],
      key_contradictions: [],
      blind_spots_identified: [],
      growth_edges: [],
      prediction_patterns: {
        how_they_would_react_to_good_news: "",
        how_they_would_react_to_bad_news: "",
        how_they_would_handle_a_crisis: "",
        how_they_would_celebrate: "",
        how_they_would_comfort_someone: "",
        how_they_would_make_a_big_decision: "",
      },
      rag_instruction: "",
    },
  };
}

module.exports = {
  SCHEMA_VERSION,
  createEmptyProfile,
};
